version: '2'
 
services:
  app:
    image: hspirdal/numbertriviaapi
    build:
      context:  ./source/api
      dockerfile: Dockerfile
    expose:
      - "8081"
 
  proxy:
    image: hspirdal/nginx
    build:
      context:  ./source/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app