version: '2'
 
services:
  app:
    image: hspirdal/numbertrivia.web
    expose:
      - "8080"
  api:
    image: hspirdal/numbertrivia.api
    expose:
      - "8081"
 
  proxy:
    image: hspirdal/numbertrivia.nginx
    ports:
      - "80:80"
    links:
      - app
      - api