version: '2'
 
services:
  app:
    image: hspirdal/numbertrivia.web
    build:
      context:  ./source
      dockerfile: ./web/Dockerfile
    expose:
      - "8080"
  api:
    image: hspirdal/numbertrivia.api
    build:
      context:  ./source
      dockerfile: ./api/Dockerfile
    expose:
      - "8081"
 
  proxy:
    image: hspirdal/numbertrivia.nginx
    build:
      context:  ./source/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
      - api